### ISSUE TITLE
Curl Timeout

### ISSUE THREAD

**Issue by Spreeuw** [postcode-nl/PostcodeNl_Api_WooCommerce#4]
2020-04-07T10:03:18+00:00 CRITICAL Uncaught PostcodeNl\InternationalAutocomplete\Exception\CurlException: Connection error number `28`: `Operation timed out after 5001 milliseconds with 0 out of -1 bytes received`. in \PostcodeNl_Api_WooCommerce\libraries\PostcodeNl\InternationalAutocomplete\Client.php:210

https://github.com/postcode-nl/PostcodeNl_Api_WooCommerce/blob/594fe0f4e01c0d431306bd5f85c34bcf2e1e9ecb/libraries/PostcodeNl/InternationalAutocomplete/Client.php#L210

should this not be caught by the plugin?

**Comment by SjonHortensius** [comment]
Are you suggesting all errors should be caught because they might break the site where the plugin is enabled?

The exception you reference is a good example of something you wouldn't want to catch, something went seriously wrong and it should be fixed to get a working site (with a working plugin)

**Comment by Spreeuw** [comment]
No, I'm suggesting that the plugin catches the error and reports to the user that the API is down (which I'm suspecting was the case here), or handle otherwise. This is technically not something that can be 'fixed' on the client side end. Note that this was only a temporary error, plugin works fine otherwise.

It looks like *none* of these exceptions thrown are caught atm:
https://github.com/postcode-nl/PostcodeNl_Api_WooCommerce/blob/594fe0f4e01c0d431306bd5f85c34bcf2e1e9ecb/libraries/PostcodeNl/InternationalAutocomplete/Client.php#L217-L237

while many of them are issues on the API server end that don't belong in the PHP error log imo.
For example the `NotFoundException` is caught in the dutch address lookup:
https://github.com/postcode-nl/PostcodeNl_Api_WooCommerce/blob/594fe0f4e01c0d431306bd5f85c34bcf2e1e9ecb/src/PostcodeNl/AddressAutocomplete/Proxy.php#L67-L70

but that same exception is not caught for autocomplete.

I would also expect exceptions like the `ForbiddenException` to be reported back to the admin in some way. You can't expect a shop owner to scan their PHP error logs for these exceptions.

**Comment by SjonHortensius** [comment]
Okay, and when you say _the user_ are you talking about the end-user that is currently ordering something, or the owner of the webshop? I see your point wrt the NotFoundException which doesn't need to end up in the PHP error log.

FWIW, the API was not experiencing any difficulties and (other) requests were successfully handled, so this might very well have been an issue that originated somewhere between the shop and the API servers.

**Comment by Spreeuw** [comment]
When an address is not found, the user that should be reported to is the end user that is entering their address, when there's an API error the user that should be reported to can be either the shop owner (getting notified of any issues with their API keys) or the end user (having an experience that is gracefully failing = not interfering with the checkout process).

**Comment by Spreeuw** [comment]
FWIW, WooCommerce has a built in logger
```php
wc_get_logger()->critical( 'Critical conditions', array( 'source' => 'postcodenl-address-autocomplete' ) );
```
https://woocommerce.wordpress.com/2017/01/26/improved-logging-in-woocommerce-2-7/

**Comment by BastiaanGrutters** [comment]
In 1.0.7 exceptions are logged by WooCommerce severity levels, see https://github.com/postcode-nl/PostcodeNl_Api_WooCommerce/releases/tag/1.0.7
