### ISSUE TITLE
Force to fill use the field

### ISSUE THREAD

**Issue by skempenaar** [postcode-nl/PostcodeNl_Api_WooCommerce#5]
Hi,

can you make a setting that people are forced to use the postcode.nl field? now our customers are still able to skip the field and by hand fill in there adreslines. so best way should be hide default woocommerce address fields until autocomplete.

![2020-07-16 12_21_06-Window](https://user-images.githubusercontent.com/68377599/87660142-def9fd80-c75e-11ea-9c3a-b75cd676b316.png)

**Comment by JozefVerhoef** [comment]
Thanks for your feedback. We have incorporated this feature in the latest release 1.0.8 (you can now configure the desired field behaviour).
