### ISSUE TITLE
Missing Translation files

### ISSUE THREAD

**Issue by Mtarnuhal** [postcode-nl/PostcodeNl_Api_WooCommerce#6]
There are no translation files available.
and creating them with loco translate doesn't seem to change the translations.

**Comment by BastiaanGrutters** [comment]
Translations should work as described here:
https://developer.wordpress.org/plugins/internationalization/localization/

I am not familiar with Loco Translate but if it creates the files in the right place and your WordPress is configured with the right locale it should work.
