### ISSUE TITLE
Remove space between housenumber and addition

### ISSUE THREAD

**Issue by johanmolen** [postcode-nl/PostcodeNl_Api_WooCommerce#7]
Hello,

Is there a possibility to remove the space between the housenumber and the addition?
So that **15 C** becomes **15C**. 

I tried doing this by overwriting the mapping but I can't combine multiple fields in the mapping, it only allows single field assignments it seems.

Also I can't find any "filters" or "actions" to overwrite the data from the API. 

Maybe I am missing something? 

Thanks in advance!

**Comment by johanmolen** [comment]
Any tips regarding this topic?

**Comment by thetankgirl** [comment]
I don't think it's advisable to do this: some housenummers (a lot in amsterdam) are in this format: Streetname 1 1
If you remove the space the housenumber will become 11

**Comment by johanmolen** [comment]
@thetankgirl Alright valid point. Then I have to look for a different solution in this case. Thank you!
