### ISSUE TITLE
Since WP 5.9 input fields are not displayed

### ISSUE THREAD

**Issue by Cattamer** [postcode-nl/PostcodeNl_Api_WooCommerce#8]
When 'Postcode and house number only' is selected together with 'Hide fields and show a formatted address instead (default)', the input fields in the checkout form for postcode are not visible anymore (CSS display: none;).

Not sure what caused this change. I solved it for now by choosing 'Show fields' but I rather would like the former setting.

EDIT: When another country is selected, the postcode and house number fields are shown. So when the page is loaded they are display: none'ed.

**Comment by JerrySmidt** [comment]
Hello. Are you using the latest version of our plugin? Because this looks a lot like something that was fixed already.

I've just tested on WP 5.9 + WooCommerce 6.2.0 with any of the default themes and could not reproduce the issue.

**Comment by Cattamer** [comment]
I'm sorry. We found te problem in deferred/delayed JS and CSS. It was just a coincidence that it happened during the same time. Case closed.
