### ISSUE TITLE
Cannot activate 2.1.1.1 version, fatal error

### ISSUE THREAD

**Issue by thetankgirl** [postcode-nl/PostcodeNl_Api_WooCommerce#9]
Warning: Use of undefined constant CURLOPT_SSL_VERIFYSTATUS - assumed 'CURLOPT_SSL_VERIFYSTATUS' (this will throw an Error in a future version of PHP) in /public_html/wp-content/plugins/PostcodeNl_Api_WooCommerce-2.1.1/libraries/PostcodeNl_Api_Client/src/PostcodeNl/Api/Client.php on line 66

This is on my staging site, not production, but I thought I would let you know.

**Comment by thetankgirl** [comment]
My curl version is 8.2.1

**Comment by valentijnh** [comment]
Same error!

**Comment by BastiaanGrutters** [comment]
Please try the new release, the dependency on cURL was replaced with the usage of WordPress remote call methods.
